server:
  port: 80
  error:
    include-stacktrace: never
  servlet:
    context-path: /hellofresh
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/menu
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

springdoc:
  api-docs:
    path: /api-docs