-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ingredient
(
    id bigint NOT NULL,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.instruction
(
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    image_url character varying(255),
    step integer NOT NULL,
    recipe_id bigint,
    PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.menu
(
    id bigint NOT NULL,
    PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.menu_recipe
(
    menu_id bigint NOT NULL,
    recipe_id bigint NOT NULL
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.nutrition_fact
(
    id bigint NOT NULL,
    carbohydrate character varying(255),
    cholesterol character varying(255),
    energy character varying(255),
    fat character varying(255),
    fiber character varying(255),
    protein character varying(255),
    saturated_fat character varying(255),
    sodium character varying(255),
    sugar character varying(255),
    PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.recipe
(
    id bigint NOT NULL,
    description character varying(255),
    title character varying(255) NOT NULL,
    nutrition_facts_id bigint,
    PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.recipe_ingredient
(
    recipe_id bigint NOT NULL,
    ingredient_id bigint NOT NULL
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.review
(
    id bigint NOT NULL,
    comment character varying(255),
    rating integer,
    recipe_id bigint NOT NULL,
    PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public.instruction
    ADD FOREIGN KEY (recipe_id)
    REFERENCES public.recipe (id)
    NOT VALID;


ALTER TABLE public.menu_recipe
    ADD FOREIGN KEY (menu_id)
    REFERENCES public.menu (id)
    NOT VALID;


ALTER TABLE public.menu_recipe
    ADD FOREIGN KEY (recipe_id)
    REFERENCES public.recipe (id)
    NOT VALID;


ALTER TABLE public.recipe
    ADD FOREIGN KEY (nutrition_facts_id)
    REFERENCES public.nutrition_fact (id)
    NOT VALID;


ALTER TABLE public.recipe_ingredient
    ADD FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredient (id)
    NOT VALID;


ALTER TABLE public.recipe_ingredient
    ADD FOREIGN KEY (recipe_id)
    REFERENCES public.recipe (id)
    NOT VALID;


ALTER TABLE public.review
    ADD FOREIGN KEY (recipe_id)
    REFERENCES public.recipe (id)
    NOT VALID;

END;